# fly.toml app configuration file generated for strenvo-landing on 2025-08-10T15:01:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'strenvo-landing'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
